# Generated by Django 6.0.4 on 2026-04-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_department_remove_course_description_and_more'),
        ('grades', '0001_initial'),
        ('students', '0002_alter_student_options_remove_student_enrollment_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'course')},
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=2),
        ),
        migrations.RemoveField(
            model_name='grade',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='exam_name',
        ),
    ]
